on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.6 sh -c "cd /checkout && apk update && apk add ruby && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.7 sh -c "cd /checkout && apk add ruby && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.8 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.9 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.10 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.11 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout alpine:3.12 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.6 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.7 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.8 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.9 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.10 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.11 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine3.12 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:2.3-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:2.4-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:2.5-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:2.6-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:2.7-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -e CI -v $(pwd):/checkout ruby:alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1

# packages    ruby docker hub
# 3.12 2.7.1               2.5.8 2.6.6 2.7.1
# 3.11 2.6.6        2.4.10 2.5.8 2.6.6 2.7.1
# 3.10 2.5.8        2.4.10 2.5.8 2.6.6 2.7.1
# 3.9  2.5.8        2.4.9  2.5.7 2.6.5 2.7.0p1
# 3.8  2.5.8  2.3.8 2.4.6  2.5.5 2.6.3
# 3.7  2.4.10 2.3.8 2.4.5  2.5.3 2.6.0
# 3.6  2.4.6        2.4.5  2.5rc
# 3.5  2.3.8
# 3.4  2.3.7  2.3.7 2.4.4
# 3.3  2.2.9
