on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: docker run -v $(pwd):/checkout alpine:3.6 sh -c "cd /checkout && apk update && apk add ruby && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout alpine:3.7 sh -c "cd /checkout && apk add ruby && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout alpine:3.8 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout alpine:3.9 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout alpine:3.10 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout alpine:3.11 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout alpine:3.12 sh -c "cd /checkout && apk add ruby ruby-etc && gem install -N bundler && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.6 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.7 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.8 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.9 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.10 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.11 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine3.12 sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:2.3-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:2.4-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:2.5-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:2.6-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:2.7-alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
    - run: docker run -v $(pwd):/checkout ruby:alpine sh -c "cd /checkout && rm -f Gemfile.lock && bundle install && ruby test.rb"
      timeout-minutes: 1
